### ISSUE TITLE
hook "cancelProduct" should be "actionProductCancel"

### ISSUE THREAD

**Issue by pjrp** [thirtybees/loyalty#3]
Loyalty points aren't updated when a product quantity is canceled in admin orders (using "Cancel products" button and form)

The module hooks to "cancelProduct" but AdminOrdersController calls for "actionProductCancel".

Submitted a pull request but what about existing installations?  Any recommendation on updating the hook without reinstall?

**Comment by getdatakick** [comment]
There exists hook alias for `actinProductCancel` - https://github.com/thirtybees/thirtybees/blob/e236ccfe7e4761803b88adbded7ce30a6e25c873/install-dev/data/xml/hook_alias.xml#L160-L163

**Comment by pjrp** [comment]
Just tested in a fresh dev installation and you are absolutely right hook alias exists in the database.
This issue was in an old thirty bees installation. Hook alias table is somewhat empty... will update it with complete alias entries.
